#!/usr/bin/env python3
"""Debug: print exact SQL generated by run_combo"""
import sys
sys.path.insert(0, '/home/gjtmux/.hermes/skills/tushare-clickhouse-direct/scripts')
from ch_query import _ch_query as ch_query

BASE = '2026-05-06'
HIST = '2020-01-01'
BOARD = "sd.ts_code NOT LIKE '30%' AND sd.ts_code NOT LIKE '688%' AND sd.ts_code NOT LIKE '920%' AND sd.ts_code NOT LIKE '%ST%'"
WF = "ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING"

BASIC_JOIN = """
LEFT JOIN (
    SELECT ts_code, trade_date, volume_ratio, turnover_rate, pe, pb, circ_mv, dv_ttm
    FROM (SELECT * FROM tushare.tushare_daily_basic FINAL) AS db
) b ON w.ts_code = b.ts_code AND w.trade_date = b.trade_date
"""

params_sql = "w.pct_chg >= 4 AND w.amplitude >= 7 AND b.volume_ratio >= 1.3 AND b.pe > 0 AND b.pe <= 15 AND b.pb > 0 AND b.pb <= 2 AND b.circ_mv <= 300000"

# Print the exact SQL from run_combo
sql = f"""
    WITH sd_windowed AS (
        SELECT sd.ts_code, sd.trade_date, sd.close, sd.pct_chg, sd.high, sd.low, sd.pre_close,
               (sd.high - sd.low) / NULLIF(sd.pre_close, 0) * 100 AS amplitude,
               leadInFrame(sd.close, 5) OVER (PARTITION BY sd.ts_code ORDER BY sd.trade_date {WF}) AS close_5d
        FROM (SELECT * FROM tushare.tushare_stock_daily FINAL) AS sd
        WHERE sd.trade_date >= '{HIST}' AND sd.trade_date <= '{BASE}'
          AND {BOARD}
    ),
    combo AS (
        SELECT w.ts_code, w.trade_date, w.close, w.pct_chg, w.amplitude, w.close_5d,
               (w.close_5d / w.close) - 1 AS ret_5d
        FROM sd_windowed w
        {BASIC_JOIN}
        WHERE {params_sql}
          AND w.trade_date >= '{HIST}' AND w.trade_date <= '{BASE}'
    )
    SELECT
        COUNT(*) AS signal_count,
        round(AVG(ret_5d) * 100, 2) AS avg_ret_5d_pct,
        round(COUNT(CASE WHEN ret_5d > 0 THEN 1 END) * 100.0 / COUNT(*), 2) AS win_rate_5d_pct
    FROM combo
    WHERE ret_5d IS NOT NULL
"""

print("=== Generated SQL ===")
print(sql)
print("=== END SQL ===")

# Now run it
r = ch_query(sql)
print(f"\nResult: {r}")
